services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:local
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["dev"]

  transactions-service:
    build:
      context: ./Transactions
      dockerfile: Dockerfile
    image: finance-tracker-service:local
    container_name: finance-tracker-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["dev"] 

  db:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    profiles: ["dev"]

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    profiles: ["dev"]


  grafana:
      image: grafana/grafana:latest
      container_name: ${GRAFANA_CONTAINER_NAME}
      env_file:
        - .env
      volumes: 
        - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      ports:
        - ${GRAFANA_PORT}:${GRAFANA_PORT}
      depends_on:
        db:
          condition: service_healthy
      restart: unless-stopped
      profiles: ["dev"]
  
  test-db:
    image: postgres:16
    container_name: test-db
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - "5433:5432"
    profiles: ["test"]
    health-check:
      test: ["CMD-SHELL", "pg_isready", "-U test-user", "-d test-db"]
      interval: 5s
      timeout: 5s
      retries: 10
      

volumes:
  pg_data:
